"""
Django settings for global_geo project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '49$8993!fae5wf-1^!sam*-2h$#6kv)di$c0tv(el-q^pgy-_@'
SITE_ID = 1
STATIC_URL	=	'/static/'
STATICFILES_DIRS	=	(os.path.join(BASE_DIR,	"static"),)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = (
	'user',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.flatpages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'geoposition',
    'django_markdown',
    'django_countries',
    'geolocalisation',
    'django_static_jquery',
    'contact',
    'core',
)

from django.core.urlresolvers import reverse_lazy

LOGIN_REDIRECT_URL	=	reverse_lazy('localisation_list')
LOGIN_URL	=	reverse_lazy('dj-auth:login')
LOGOUT_URL	=	reverse_lazy('dj-auth:logout')

MIDDLEWARE_CLASSES = (
	'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
   
)

ROOT_URLCONF = 'global_geo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
       # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
         'loaders': [
			#('django.template.loaders.cached.Loader',	[
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
           # ]),
        ],
        },
    },
]

CACHES = {
	'default': {
		'BACKEND':'django.core.cache.backends.dummy.DummyCache',
	}
}

CACHE_MIDDLEWARE_ALIAS	=	'default'

WSGI_APPLICATION = 'global_geo.wsgi.application'

AUTH_USER_MODEL = 'user.User'
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'global_geo_db',
        'USER': 'global_geo_user',
        'PASSWORD': 'globalgeouser2017',
        'HOST': 'localhost',
        'PORT':'',
        
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyArZXCuRpYea7VDOw44PfkRTK0UjhAqCFQ'
GEOPOSITION_MARKER_OPTIONS = {
         'cursor': 'move'
     }
GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 100,
}
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only
SERVER_EMAIL	=	'contact@eces.com'
DEFAULT_FROM_EMAIL	=	'no-reply@deces.com'
EMAIL_SUBJECT_PREFIX	=	'[Localisation Identite]	'
MANAGERS	=	(('Us',	'casup@deces.com'),)

FIXTURE_DIRS = (os.path.join(BASE_DIR, 'fixtures'), )
